#!/usr/bin/env python3
"""Generate the faktory-dao BE deploy templates from the .clar sources.

WHY THIS EXISTS. Contract source has a hard 100,000-byte protocol limit.
fakfun-wallet-v14 shipped at 90,595 bytes WITH its comments; the v15 attempt added
enough explanatory prose to reach 102,803 and was rejected by @stacks/transactions
before it ever reached the network:

    String length exceeds maximum bytes 100000

The .clar sources are now COMMENT-FREE, so this script is an identity transform
plus three guards: no comment may creep back in, parens must balance, and no
artifact may exceed the limit. Rationale for the contracts lives in
README-v5-v15-design.md and in git history, not in the bytes.

Run with --check in CI or before a deploy to prove the committed templates match
the sources.

The .clar and the template are byte-identical again, so verifying an on-chain
contract can be done against either.
"""
import sys
from pathlib import Path

SRC = Path(__file__).parent / "contracts"
DST = Path("/home/raphastacks/projects/faktory-dao/backend/server/utils")
LIMIT = 100_000

# v9 and v5 are ON CHAIN and shipped WITH comments (blocks 8703790 / 8703793); v15
# was rejected for exceeding the size limit. Names cannot be reused, so the
# comment-free generation is v10 / v6 / v16. The older templates stay in the BE for
# the record but are not regenerated here.
TARGETS = [
    ("smart-wallet-standard-auth-helpers-v10", "SMART_WALLET_STANDARD_AUTH_HELPERS_V10_TEMPLATE"),
    ("juice-safe-v6", "JUICE_SAFE_V6_TEMPLATE"),
    ("fakfun-wallet-v16", "FAKFUN_WALLET_V16_TEMPLATE"),
]


def strip_clarity(src: str) -> str:
    """Remove Clarity comments and backticks, preserving the visual structure.

    Three rules, and the third is the one that matters:

      1. Blank lines already in the source survive; runs of them collapse to one.
      2. A trailing comment on a code line is cut, the code stays.
      3. A dropped comment BLOCK leaves a blank line in its place when it sat
         between two code lines.

    Rule 3 exists because in this codebase the comment blocks ARE the separators.
    The constants section has no blank lines of its own -- each group is introduced
    by a comment -- so stripping without rule 3 collapses forty declarations into
    one undifferentiated wall.

    String-literal aware: a ';' inside a double-quoted string is not a comment.
    No current source has one; the guard costs nothing and a future memo could.
    """
    out = []
    dropped_comment = False
    for line in src.split("\n"):
        raw_blank = line.strip() == ""
        in_str = False
        cut = None
        i = 0
        while i < len(line):
            c = line[i]
            if c == '"':
                in_str = not in_str
            elif c == ";" and not in_str:
                cut = i
                break
            i += 1
        code = (line[:cut] if cut is not None else line).replace("`", "").rstrip()

        if code:
            # rule 3: a comment block stood here and separated two code lines
            if dropped_comment and out and out[-1] != "":
                out.append("")
            dropped_comment = False
            out.append(code)
        elif raw_blank:
            # rule 1: a real blank already does the separating
            dropped_comment = False
            if out and out[-1] != "":
                out.append("")
        else:
            # comment-only line
            dropped_comment = True

    while out and out[-1] == "":
        out.pop()
    return "\n".join(out) + "\n"


def main():
    check = "--check" in sys.argv
    failed = False
    for name, const in TARGETS:
        clar = (SRC / f"{name}.clar").read_text()
        code = strip_clarity(clar)

        assert ";" not in code.replace('"', ""), f"{name}: a ';' survived stripping"
        assert "`" not in code, f"{name}: a backtick survived"
        assert code.count("(") == code.count(")"), f"{name}: parens unbalanced after strip"
        assert clar.count("(") == clar.count(")"), f"{name}: .clar parens unbalanced"

        head = (
            f"// {name} source. GENERATED by build-be-templates.py -- do not hand-edit.\n"
            f"// Comment-free and byte-identical to the .clar. Contract source has a hard\n"
            f"// {LIMIT}-byte limit; comments in the source are what broke the v15 deploy.\n"
        )
        body = f"{head}\nexport const {const} = `{code}`;\n"
        path = DST / f"{name}-template.ts"

        head_room = LIMIT - len(code)
        status = "ok" if head_room >= 0 else f"OVER by {-head_room}"
        saved = len(clar) - len(code)
        print(
            f"  {name:40s} .clar={len(clar):6d} -> deployed={len(code):6d} "
            f"(-{saved:5d})  headroom={head_room:6d}  {status}"
        )
        if head_room < 0:
            failed = True

        if check:
            if not path.exists() or path.read_text() != body:
                print(f"     STALE: {path.name} does not match")
                failed = True
        else:
            path.write_text(body)

    if failed:
        sys.exit(1)
    print("  all templates " + ("verified" if check else "written"))


if __name__ == "__main__":
    main()
