;; An nftmarket-trait double, recording each opcode branch the wallet dispatches to.
(impl-trait 'SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.fakfun-nftmarket-trait.nftmarket-trait)
(use-trait nft-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)
(use-trait ft-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait)
(define-data-var last (string-ascii 16) "none")
(define-read-only (get-last) (var-get last))
(define-public (list-nft (id uint) (nft <nft-trait>) (ft <ft-trait>) (price uint))
  (begin (var-set last "list") (if true (ok true) (err u0))))
(define-public (buy-nft (id uint) (nft <nft-trait>) (ft <ft-trait>))
  (begin (var-set last "buy") (if true (ok true) (err u0))))
(define-public (unlist-nft (id uint) (nft <nft-trait>))
  (begin (var-set last "unlist") (if true (ok true) (err u0))))
(define-public (update-price (id uint) (price uint))
  (begin (var-set last "price") (if true (ok true) (err u0))))
(define-public (update-listing-ft (id uint) (ft <ft-trait>) (price uint))
  (begin (var-set last "ft") (if true (ok true) (err u0))))
