;; A prelaunch-trait double.
(impl-trait 'SPV9K21TBFAK4KNRJXF5DFP8N7W46G4V9RCJDC22.prelaunch-faktory-trait-v1.prelaunch-trait)
(use-trait faktory-token 'SP3XXMS38VTAWTVPE5682XSBFXPTH7XCPEBTX8AN2.faktory-trait-v1.sip-010-trait)
(define-data-var seats uint u0)
(define-data-var refunds uint u0)
(define-data-var claims uint u0)
(define-data-var airdrops uint u0)
(define-read-only (get-seats) (var-get seats))
(define-read-only (get-refunds) (var-get refunds))
(define-read-only (get-claims) (var-get claims))
(define-read-only (get-airdrops) (var-get airdrops))
(define-public (buy-up-to (n uint) (who (optional principal)))
  (begin (var-set seats (+ (var-get seats) n)) (if true (ok n) (err u0))))
(define-public (refund (who (optional principal)))
  (begin (var-set refunds (+ (var-get refunds) u1)) (if true (ok u1) (err u0))))
(define-public (claim (token <faktory-token>))
  (begin (var-set claims (+ (var-get claims) u1)) (if true (ok u1) (err u0))))
(define-public (claim-on-behalf (token <faktory-token>) (who principal))
  (begin (var-set claims (+ (var-get claims) u1)) (if true (ok u1) (err u0))))
(define-public (trigger-fee-airdrop)
  (begin (var-set airdrops (+ (var-get airdrops) u1)) (if true (ok u1) (err u0))))
(define-public (is-market-open) (if true (ok true) (err u0)))
(define-public (get-seat-price) (if true (ok u1000000) (err u0)))
